project_id = "wbeomprrrmteftumwljf"

[functions.secure-signup]
verify_jwt = false

[functions.seed-demo-candidates]
verify_jwt = true

[functions.unlock-profile]
verify_jwt = true

[functions.purchase-credits]
verify_jwt = true