-- Update autogenerated candidate usernames to realistic ones
DO $$
DECLARE
  profile_record RECORD;
  new_username TEXT;
  name_parts TEXT[];
  first_name TEXT;
  last_name TEXT;
  username_suffix TEXT;
BEGIN
  -- Loop through all profiles with autogenerated candidate_ usernames
  FOR profile_record IN 
    SELECT id, full_name, email
    FROM profiles
    WHERE username LIKE 'candidate_%'
    AND length(username) > 20  -- Only target autogenerated ones with random IDs
  LOOP
    -- Try to extract name from full_name or email
    IF profile_record.full_name IS NOT NULL AND profile_record.full_name != '' THEN
      name_parts := string_to_array(lower(trim(profile_record.full_name)), ' ');
      first_name := name_parts[1];
      last_name := COALESCE(name_parts[array_length(name_parts, 1)], name_parts[1]);
    ELSE
      -- Fallback to email
      first_name := split_part(profile_record.email, '@', 1);
      last_name := '';
    END IF;

    -- Generate realistic username with random variation
    CASE (random() * 7)::int
      WHEN 0 THEN new_username := first_name || '_' || last_name;
      WHEN 1 THEN new_username := first_name || last_name || '_sec';
      WHEN 2 THEN new_username := first_name || '.' || last_name;
      WHEN 3 THEN new_username := 'cyber_' || first_name || '_' || last_name;
      WHEN 4 THEN new_username := first_name || '_' || last_name || '_analyst';
      WHEN 5 THEN new_username := last_name || '_' || first_name;
      ELSE new_username := first_name || '_' || last_name || '_pro';
    END CASE;

    -- Ensure username doesn't already exist by appending numbers if needed
    WHILE EXISTS (SELECT 1 FROM profiles WHERE username = new_username AND id != profile_record.id) LOOP
      new_username := new_username || floor(random() * 99 + 1)::text;
    END LOOP;

    -- Update the profile
    UPDATE profiles
    SET username = new_username
    WHERE id = profile_record.id;
    
    RAISE NOTICE 'Updated username for profile %: %', profile_record.id, new_username;
  END LOOP;
END $$;