-- Update autogenerated candidate usernames (max 20 chars)
DO $$
DECLARE
  profile_record RECORD;
  new_username TEXT;
  name_parts TEXT[];
  first_name TEXT;
  last_name TEXT;
BEGIN
  FOR profile_record IN 
    SELECT id, full_name, email
    FROM profiles
    WHERE username LIKE 'candidate_%'
    AND length(username) >= 18
  LOOP
    -- Extract name
    IF profile_record.full_name IS NOT NULL AND profile_record.full_name != '' THEN
      name_parts := string_to_array(lower(trim(profile_record.full_name)), ' ');
      first_name := substring(name_parts[1], 1, 10);
      last_name := substring(COALESCE(name_parts[array_length(name_parts, 1)], ''), 1, 10);
    ELSE
      first_name := substring(split_part(profile_record.email, '@', 1), 1, 10);
      last_name := '';
    END IF;

    -- Generate short username (max 20 chars)
    CASE (random() * 4)::int
      WHEN 0 THEN new_username := substring(first_name || '_' || last_name, 1, 20);
      WHEN 1 THEN new_username := substring(first_name || last_name, 1, 17) || '_se';
      WHEN 2 THEN new_username := substring(last_name || '_' || first_name, 1, 20);
      WHEN 3 THEN new_username := substring(first_name, 1, 10) || '_sec' || substring(last_name, 1, 6);
      ELSE new_username := substring(first_name || '_' || last_name, 1, 17) || '_pr';
    END CASE;

    -- Ensure unique and under 20 chars
    WHILE EXISTS (SELECT 1 FROM profiles WHERE username = new_username AND id != profile_record.id) LOOP
      new_username := substring(new_username, 1, 18) || floor(random() * 99)::text;
    END LOOP;

    -- Final length check
    IF length(new_username) > 20 THEN
      new_username := substring(new_username, 1, 20);
    END IF;

    UPDATE profiles
    SET username = new_username
    WHERE id = profile_record.id;
    
  END LOOP;
END $$;