-- Update autogenerated candidate usernames (max 20 chars)
DO $$
DECLARE
  profile_record RECORD;
  new_username TEXT;
  name_parts TEXT[];
  first_name TEXT;
  last_name TEXT;
  first_initial TEXT;
BEGIN
  FOR profile_record IN 
    SELECT id, full_name, email
    FROM profiles
    WHERE username LIKE 'candidate_%'
    AND length(username) >= 18
  LOOP
    -- Extract names
    IF profile_record.full_name IS NOT NULL AND profile_record.full_name != '' THEN
      name_parts := string_to_array(lower(trim(profile_record.full_name)), ' ');
      first_name := name_parts[1];
      last_name := COALESCE(name_parts[array_length(name_parts, 1)], name_parts[1]);
      first_initial := left(first_name, 1);
    ELSE
      first_name := split_part(profile_record.email, '@', 1);
      last_name := '';
      first_initial := left(first_name, 1);
    END IF;

    -- Generate short username variations (under 20 chars)
    CASE (random() * 6)::int
      WHEN 0 THEN 
        -- firstname_lastname (trim if needed)
        new_username := substring(first_name || '_' || last_name, 1, 20);
      WHEN 1 THEN 
        -- firstname_l
        new_username := first_name || '_' || left(last_name, 1);
      WHEN 2 THEN 
        -- f_lastname
        new_username := first_initial || '_' || last_name;
      WHEN 3 THEN 
        -- firstnamelastname
        new_username := substring(first_name || last_name, 1, 20);
      WHEN 4 THEN 
        -- firstname_sec
        new_username := substring(first_name, 1, 15) || '_sec';
      WHEN 5 THEN
        -- lastname_firstname (trim if needed)
        new_username := substring(last_name || '_' || first_name, 1, 20);
      ELSE 
        -- cyber_firstname
        new_username := 'cyber_' || substring(first_name, 1, 13);
    END CASE;

    -- Ensure uniqueness by appending number if needed
    WHILE EXISTS (SELECT 1 FROM profiles WHERE username = new_username AND id != profile_record.id) LOOP
      -- Remove last char and add number to stay under 20 chars
      new_username := substring(new_username, 1, 18) || floor(random() * 99 + 1)::text;
      new_username := substring(new_username, 1, 20);
    END LOOP;

    -- Update profile
    UPDATE profiles
    SET username = new_username
    WHERE id = profile_record.id;
    
    RAISE NOTICE 'Updated: % -> %', profile_record.full_name, new_username;
  END LOOP;
END $$;